### PR TITLE
CDP-1765 remove deprecated mysql connection properties

### PR DESCRIPTION
**Pull request by miklos-martin**
since 8.0.13, sslMode is configurable similarly to postgres

### CODE REVIEW

**Review by fugafree — COMMENTED** [review]
LGTM

**Comment by miklos-martin** [comment]
I think we should also fix the SSL config for the it tests to be able to verify at least the root CA. Let’s postpone this merge for the next week.

**Comment by fugafree** [comment]
Recap: this change is about removing the usage of two deprecated parameter of mysql driver: useSSL and verifyServerCertificate. And replace them with the new param: sslMode.

See related MySQL documentation:
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html
> Server authentication via server certificate verification is enabled when the Connector/J connection property sslMode is set to VERIFY_CA or VERIFY_IDENTITY. If sslMode is not set, server authentication via server certificate verification is enabled when the legacy properties useSSL AND verifyServerCertificate are both true.

After this change, all services using these option of connector collection should be changed.

**Comment by fugafree** [comment]
@miklos-martin what is the status of this task? Do we want to improve the certificate validation in tests?

**Pull request merged**
